language: ruby
rvm: 
- 2.2.0
before_install:
- travis_retry gem install jekyll --no-ri --no-rdoc
- sudo apt-get update -y
- sudo apt-get install -y apache2
script: ./.run-tests.sh
after_success:
- travis_retry gem install percy-cli
- jekyll build -d ~/_site
- percy snapshot ~/_site --repo "codeforamerica/codeforamerica.org" --autoload_remote_resources
branches:
  only:
    - master
notifications:
  webhooks:
    urls:
      - http://cfa-project-monitor.herokuapp.com/projects/325e607a-561b-4e33-9fe0-b2f38d6b384b/status
      - http://www.codeforamerica.org/cgi-bin/travis-webhook.cgi
