language: ruby
before_install:
- travis_retry gem install jekyll --no-ri --no-rdoc
- sudo apt-get install -y apache2
script: ./.run-tests.sh
branches:
  only:
    - master
notifications:
    webhooks: http://cfa-project-monitor.herokuapp.com/projects/325e607a-561b-4e33-9fe0-b2f38d6b384b/status
